export { SearchForm } from './SearchForm'
export { Answer } from './Answer'
export { Question } from './Question'
export { Quiz } from './Quiz'
export { Login } from './Login'
export { Inputs } from './Test'
export { Highscores } from './Highscores'
export { FinalScores } from './FinalScores'