services:
  api:
    container_name: demo_test_api
    environment: 
      - PGUSER=admin
      - PGHOST=db
      - PGPASSWORD=scorespass
      - PGDATABASE=users
      - PGPORT=5432
      - NODE_ENV=test
    depends_on:
      - db
    tty: true
  db:
    container_name: demo_test_db
    volumes:
      - "test_db:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=users
      - POSTGRES_PASSWORD=scorespass
volumes:
  test_db:
networks: 
  default:
    name: demo_app_test
