services:
  api:
    container_name: scores_dev_api
    ports:
      - 3000:3000
    environment:
      - PGUSER=admin
      - PGHOST=db
      - PGPASSWORD=scorespass
      - PGDATABASE=scoreboard
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm start"

  db:
    container_name: scores_dev_db
    volumes:
      - 'dbdata:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=score_test
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=scorespass
volumes:
  dbdata:
networks:
  default:
    name: scores_app_dev
