version: '3'
services:
  api:
    container_name: heroku_api
    image: node:14.17.2
    ports:
      - 3000:3000
    working_dir: /code
    volumes:
      - type: bind
        source: ./
        target: /code
    environment:
      - PGUSER=admin
      - PGHOST=db
      - PGPASSWORD=scorespass
      - PGDATABASE=users
      - PGPORT=5432
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run start"

  db:
    container_name: heroku_db
    image: postgres:latest
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=scorespass
    volumes:
      - './db/migrations:/docker-entrypoint-initdb.d/:ro'

# volumes:
#   dbdata:
