version: '3'
services:
  api:
    container_name: heroku_api
    image: node:14.17.2
    ports:
      - 3000:3000
    environment:
      - PGUSER=admin
      - PGHOST=db
      - PGPASSWORD=scorespass
      - PGDATABASE=scoreboard
      - PGPORT=5432
      - NODE_ENV=development
    volumes:
      - type: bind
        source: ./
        target: /code
    working_dir: /code
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    container_name: heroku_db
    image: postgres:latest
    volumes:
      - './db/migrations:/docker-entrypoint-initdb.d/:ro'
    environment:
      - POSTGRES_DB=scoreboard
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=scorespass

# volumes:
#   dbdata:
