export { StartPage } from './StartPage'
export { NewGamePage } from './NewGamePage'
export { QuizPage } from './QuizPage'
export { HighscorePage } from './HighscorePage'
export { FinalScorePage } from './FinalScorePage'
