export { Home } from './Home'
export { QuizPage } from './QuizPage'
export { LoginPage } from './LoginPage'
export { HighscorePage } from './HighscorePage'
export { FinalScorePage } from './FinalScorePage'
export { StartPage } from './StartPage'
